version: "3.4"
services:
  manager:
    build: ./build-manager
    restart: unless-stopped
    environment:
      - LATTICE_MANAGER_PORT=
      - LATTICE_CONNECT_PORT=
    ports:
      - "3001:3001"
    image: "manager.lattice-manager.dnp.dappnode.eth:1.0.0"
